### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'load_weights'

### ISSUE THREAD

**Issue by Nixon1979** [Rudrabha/LipGAN#11]
Environment -

Ubuntu 18.4
Tensorflow-GPU - 1.18
Keras tired with 2.2.4 and 2.3.1
cuda-9.0

Tried to import keras from TensorFlow but in all cases getting the following error.

Model Created

Traceback (most recent call last):
  File "batch_inference.py", line 228, in <module>
    main()
  File "batch_inference.py", line 206, in main
    model.load_weights(args.checkpoint_path)
AttributeError: 'tuple' object has no attribute 'load_weights'

**Comment by Nixon1979** [comment]
Sorry my bad .. closing this.. it was a path issue.

**Comment by vishalsharma345** [comment]
HI @Nixon

> Sorry my bad .. closing this.. it was a path issue.

HI Nixon,

i am getting same issue (screenshot attached).  Could you please let me know how did you fix the issue.
![error](https://user-images.githubusercontent.com/38868982/75228039-5a213e00-57d5-11ea-831d-765261014dfd.png)

Vishal

**Comment by Nixon1979** [comment]
Specify the path along with the ligan checkpoint file name, not only the
folder path
