### ISSUE TITLE
About Chin movement

### ISSUE THREAD

**Issue by chikiuso** [Rudrabha/LipGAN#14]
Hi, I see the result that the Chin isn't moving and looks like diecut, may I ask how to make it include the chin movement? thanks.

**Comment by prajwalkr** [comment]
Could you please post an example video here? The model takes into account the whole face, including the chin.

**Comment by chikiuso** [comment]
Hi @prajwalkr , it is for you have a look, thanks :

[https://www.dailymotion.com/video/x7shv57]

**Comment by prajwalkr** [comment]
Thanks! I just had a look at it and this is an issue with the face detection which can be easily fixed. 

If you look closely you can see that the face is detected only till a particular point and it has excluded the chin. You can correct this by specifying the `--pads` argument. Please increase the bottom padding to include the chin. 

`python batch_inference.py --pads 0 --pads 10 --pads 0 --pads 0  --checkpoint_path ....`

The above will add a bottom padding of 10 pixels. Change the parameter according to your needs. Refer this [line](https://github.com/Rudrabha/LipGAN/blob/690d7b89cab4a5428f3a781b67fef1d12bbd3bd5/batch_inference.py#L25) for more info.

**Comment by chikiuso** [comment]
thanks for your help! your work is really important, and will make the history!
