### ISSUE TITLE
Without mathlab

### ISSUE THREAD

**Issue by rebotnix** [Rudrabha/LipGAN#16]
Thanks for this great project. Is there a way to process the audio without having matlab?

**Comment by prajwalkr** [comment]
I will push a new branch which would be a version of the project without the MATLAB dependency in less a week. I will reply to this issue when I do so.

**Comment by prajwalkr** [comment]
Please check out the new branch `fully_pythonic`. Please raise new issues regarding any bugs that you might encounter.
