### ISSUE TITLE
MAT file required

### ISSUE THREAD

**Issue by ashneg** [Rudrabha/LipGAN#22]
Fully pythonic branch doesn't works without the mat file

**Comment by prajwalkr** [comment]
Please post your exact error log here.

**Comment by ashneg** [comment]
Tried it with a still image. The log is below:
`python3 batch_inference.py --checkpoint_path ./logs/lipgan_residual_mel.h5 --face ../try.jpg --audio ../tryAudio.wav --results_dir ./results
Using TensorFlow backend.
/home/ashneg/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ashneg/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ashneg/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ashneg/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ashneg/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ashneg/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
usage: batch_inference.py [-h] --checkpoint_path CHECKPOINT_PATH
                          [--face_det_checkpoint FACE_DET_CHECKPOINT] --face
                          FACE --audio AUDIO --mat MAT
                          [--results_dir RESULTS_DIR] [--static STATIC]
                          [--fps FPS] [--max_sec MAX_SEC]
                          [--pads PADS [PADS ...]]
                          [--face_det_batch_size FACE_DET_BATCH_SIZE]
                          [--lipgan_batch_size LIPGAN_BATCH_SIZE]
                          [--n_gpu N_GPU]
batch_inference.py: error: the following arguments are required: --mat
`

**Comment by prajwalkr** [comment]
You are not using the code from the `fully_pythonic` branch. I rechecked and for this branch, `--mat` is not even an argument. Please switch branch to `fully_pythonic` after cloning the repo to resolve this issue. I will add this instruction in the README.
