### ISSUE TITLE
librosa's mfcc extraction 

### ISSUE THREAD

**Issue by ArashHosseini** [Rudrabha/LipGAN#3]
@prajwalkr do you think its possible to use librosa instead of matlab?

**Comment by prajwalkr** [comment]
Hi, thanks for checking out the repository. Yes, it is possible to use Librosa. We had initially used MATLAB for direct, fair comparison with the "You Said That?" paper. 

But very recently we had tried a bit with librosa and the results looked alright. You should definitely give it a go without hesitation :)

**Comment by schilpr** [comment]
@prajwalkr I know you closed this issue, sorry to respond to it.

Could you share your librosa code to replace the Matlab dependency? I have no access to Matlab and would like to continue my research without first figuring out librosa. 

Thank you.

**Comment by prajwalkr** [comment]
Hello, so very recently (a few days back), we have coded a rough version of the model to use Mel spectrograms from Librosa. 

I will polish it a bit and share it in the early first week of March, as I am currently held up with other deadlines. I hope that is alright :) 

I will push it to a new branch where the whole thing would work independently of MATLAB.

**Comment by schilpr** [comment]
@prajwalkr that's awesome, thank you very much for the great work on this project.

**Comment by prajwalkr** [comment]
Please check out the new branch `fully_pythonic`. Please raise new issues regarding any bugs that you might encounter.
