### ISSUE TITLE
epoch size during training

### ISSUE THREAD

**Issue by dlwogns0128** [Rudrabha/LipGAN#32]
In train.py or train_unet.py, the default epoch size is 20000000.
But, you trained model 20 epochs with LRS2 dataset in the paper. 
How many epochs do I have to train the model if I want to get accuracy like your proposed trained weights?

Thanks!

**Comment by prajwalkr** [comment]
Please train for around 20 epochs on LRS2. We have set that so that we can just stop the training whenever desired (as convergence will be different for different datasets).
