### ISSUE TITLE
CONTINIOUS PLAYING

### ISSUE THREAD

**Issue by Leonthegamer12** [Rudrabha/LipGAN#33]
I want to create a chatbot that uses text to speech and lipgan for face animation. Is there a way that the lipgan can be used in real time and create something like a talking avatar that uses text to speech live? Any help will be valuable

**Comment by Rudrabha** [comment]
I guess real-time is a subjective term and it varies for each problem. For LipGAN, we will need at least a 350 ms audio window and an identity frame with the target head-pose for the model to work. So as long as you can feed a 350 ms audio window and a face with the target pose continuously the model is good to go in theory. The output from the model itself takes some time to generate. The major time-consuming steps that can be avoided in your case are - 
1. Face detection. You can provide an already cropped face to the model. 
2. You should also load the weights only once and then continuously feed the audio chunks.
3. Some sort of a data buffer can be created wherein you feed the audio and the face in batches, i.e. while one batch is being generated, you create the next batch.

All these can reduce the time taken to generate the output significantly.

**Comment by Leonthegamer12** [comment]
@Rudrabha thank you very much for you're response in such a short time

**Comment by chikiuso** [comment]
@Leonthegamer12 I built one , feel free to have a look :
[https://www.twitch.tv/aipictures](url)

**Comment by Leonthegamer12** [comment]
> @Leonthegamer12 I built one , feel free to have a look :
> https://www.twitch.tv/aipictures

Sorry but is there a way that you can share the code with me. There's a very similar project im working on and it would be very helpful.

**Comment by Rudrabha** [comment]
@chikiuso that is really cool :) Does it use LipGAN?

**Comment by Leonthegamer12** [comment]
> @chikiuso that is really cool :) Does it use LipGAN?

@chikiuso of course and you're source code would be very helpful

**Comment by chikiuso** [comment]
@Rudrabha thanks! and thank for your great work. I did use LipGAN in this twitch channel , I will cite your great project in my website ai.pictures as twitch panel is too small to show the paper name :)

@Leonthegamer12 the twitch channel code is composed of several recent major advancements in nlp, voice synthesis and LipGAN etc, now the code is really quite in a mess, I may be open it after I tidy it up and write some documentation, as now the installation and setting of the server is now too too complicated.

**Comment by Rudrabha** [comment]
@chikiuso Thanks!

**Comment by Leonthegamer12** [comment]
> @Rudrabha thanks! and thank for your great work. I did use LipGAN in this twitch channel , I will cite your great project in my website ai.pictures as twitch panel is too small to show the paper name :)
> 
> @Leonthegamer12 the twitch channel code is composed of several recent major advancements in nlp, voice synthesis and LipGAN etc, now the code is really quite in a mess, I may be open it after I tidy it up and write some documentation, as now the installation and setting of the server is now too too complicated.

I dont want the whole project. All i want is the part of the code that makes LipGan work in Real-Time as im having some problems there. I'll figure the rest by myself.
