### ISSUE TITLE
Keras requires TensorFlow 2.2 or higher

### ISSUE THREAD

**Issue by javaintheuk** [Rudrabha/LipGAN#35]
Hi,

I'm porting the colab version to kaggle, on the last step (after uninstalling and installing TF to a lowest version) I get:

Keras requires TensorFlow 2.2 or higher

I checked my TF version and even after uninstalling it I get: '2.3.0'  when I should have 1.14.0

Any idea why Kaggle is not allowing me to downgrade the TF version? 

Thanks

**Comment by Rudrabha** [comment]
Did you specify the version of tensorflow while installing? Normally, ``` pip install tensorflow-gpu==1.14.0 ```  should work.

**Comment by javaintheuk** [comment]
Thank you very much for getting back to me, yes I did, I think could be a Kaggle problem as I can't force it to downgrade, even after restarting. I'll dig in more... thanks

**Comment by Rudrabha** [comment]
I am closing this issue for now since the problem does not lie with the LipGAN model. However, if you find a fix, please comment down below, it might be helpful for others. :)
