### ISSUE TITLE
Inference freezes in beginning

### ISSUE THREAD

**Issue by alter-sachin** [Rudrabha/LipGAN#36]

**Comment by prajwalkr** [comment]
LLVM ERROR: out of memory. the code has crashed due to this error. We have not faced this issue? Maybe a lookup on google can point out why this error comes?

**Comment by alter-sachin** [comment]
I increased my RAM CPU and the LLVM Error goes away
But the inference does not begin. it is still stuck at 0%

**Comment by prajwalkr** [comment]
Can you add print statements in different places and figure out where it is freezing?

**Comment by alter-sachin** [comment]
It does not go ahead from this line

https://github.com/Rudrabha/LipGAN/blob/65e528449a80c048a36214d356c39e215e5a41f7/batch_inference.py#L187

**Comment by prajwalkr** [comment]
It is stuck inside the data generator then. Can you see which line inside that?

**Comment by alter-sachin** [comment]
gen = datagen(full_frames.copy(), mel_chunks)
	print("after datagen")

	for i, (img_batch, mel_batch, frames, coords) in enumerate(tqdm(gen, 
											total=int(np.ceil(float(len(mel_chunks))/batch_size)))):
		if i == 0:
			print("before create model")
			model = create_model(args, mel_step_size)
			print ("Model Created")

			model.load_weights(args.checkpoint_path)
			print ("Model loaded")

			frame_h, frame_w = full_frames[0].shape[:-1]
			print("before video writer")
			out = cv2.VideoWriter(path.join(args.results_dir, 'result.avi'), 
									cv2.VideoWriter_fourcc(*'DIVX'), fps, (frame_w, frame_h))




The after datagen print statement is outputted. so i think its in the beginning of the loop? I might be wrong...

**Comment by alter-sachin** [comment]
I receive an out of memory error again.
Is a k80 GPU enough for running this? Seems to have enough GPU RAM(25GB I think)

**Comment by alter-sachin** [comment]
Sidenote : The single image example runs quite well for me

**Comment by prajwalkr** [comment]
> I receive an out of memory error again.
> Is a k80 GPU enough for running this? Seems to have enough GPU RAM(25GB I think)

Can you paste the error message?

**Comment by alter-sachin** [comment]
LVM Error : Out of Memory

**Comment by prajwalkr** [comment]
Hello, sorry that we are unable to help you as we do not have sufficient information, nor have we faced such an error. You can try out [Wav2Lip](https://github.com/Rudrabha/Wav2Lip), which is a significant improvement of this work.
