### ISSUE TITLE
matlab issue

### ISSUE THREAD

**Issue by augustfr** [Rudrabha/LipGAN#41]
I have matlab 2020b installed on my mac. I can't figure out how to run the create_mat function. What should I be typing into the terminal?
<img width="554" alt="Screen Shot 2021-01-20 at 8 12 53 PM" src="https://user-images.githubusercontent.com/68298953/105279177-e231d400-5b5b-11eb-89f1-19dd442dfc42.png">

**Comment by Rudrabha** [comment]
The second argument should require filename.mat for running this code. In case you are unable to run the matlab code, please check out our fully pythonic_branch in https://github.com/Rudrabha/LipGAN/tree/fully_pythonic
This branch does not require matlab and will have quite similar results to the original LipGAN.
