### ISSUE TITLE
Fully_pythonic branch issue: RuntimeError: Unable to open logs/mmod_human_face_detector.dat for reading.

### ISSUE THREAD

**Issue by kindler-king** [Rudrabha/LipGAN#47]
Hello,
I had a query regarding the fully_pythonic branch execution, 
I added the necessary packages and supplied the image and .wav audio file to create the example #2 (create video using image and audio). 
python batch_inference.py --checkpoint_path logs/lipgan_residual_mel.h5 --face face.jpg --audio try.wav --results_dir results  [cmd]

The script is starting but ending abruptly with this error:
![Capture](https://user-images.githubusercontent.com/53633591/146986515-5fdcdf91-8381-45bf-912b-21bb5a77d6b9.PNG)

Where can I find the human_face_detector.dat file, I only found a link to download the pretrained Lipgan checkpoint, where to get this .dat file? Thanks a lot for your help.

**Comment by Vebrun** [comment]
I find it，did you found it now? can you tell me your env? especially tensorflow-gpu==? and keras==? and CUDA? please tall me ,thank you very much

**Comment by nastia-lado** [comment]
In case you didn't find .dat file, you can download it here:
http://dlib.net/files/mmod_human_face_detector.dat.bz2

You might have to copy and paste the link.
